export const portfolioTexts = [
  {
    header: "Runsmart",
    imageSrc: "./runsmart.webp",
    link: "https://runsmart.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/runsmart",
    description: "Верстка учебного макета интернет-магазина по продаже смарт-часов для бега. Верстка по макету из Figma.",
    instruments: "HTML, SASS, JavaScript, Gulp, PHP Mailer",
    features: "Модальные окна, форма обратной связи с валидацией, Adaptive, Slider, Burger"
  },
  {
    header: "Портфолио веб-разработчика",
    imageSrc: "./portfolio.webp",
    link: "https://portfolio.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/portfolio-template",
    description: "Верстка учебного макета сайта-портфолио веб-разработчика. Верстка по макету из Figma.",
    instruments: "HTML, SASS, JavaScript, Gulp",
    features: "Семантическая верстка, добавление страницы с политикой конфиденциальности, стилизация инпутов в форме обратной связи, использование миксинов и псевдоэлементов, Pixel Perfect, Adaptive, Burger, CSS Grid.",
  },
  {
    header: "Zlatmax",
    imageSrc: "./zlatmax.webp",
    link: "https://zlatmax.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/zlatman",
    description: "Верстка учебного макета интернет-магазина по продаже ножей ручной работы. Верстка по макету из Figma.",
    instruments: "HTML, SСSS, JavaScript, Gulp, Webpack",
    features: "Модальные окна, трехуровневое меню, кастомные слайдеры, аккордеон, tips, адаптив без брейкпоинтов, Burger.",
  },
  {
    header: "ToDo List React + Redux",
    imageSrc: "./todoreact.webp",
    link: "https://todo.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/todoList-react-redux",
    description: "Приложение - Список дел на React с использованием библиотеки Redux. Типичное CRUD-приложение, созданное с помощью React и Redux. Позволяет добавлять или удалять дела, отмечать как выполненные, фильтровать по признакам. Добавлена возможность работы без мышки.",
    instruments: "HTML, SСSS, JavaScript, React, Redux",
    features: "SPA, React, Redux",
  },
  {
    header: "Movie Library",
    imageSrc: "./movielib.webp",
    link: "https://movielib.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/mov-lib-react",
    description: "Single Page Application, созданное с помощью библиотеки React и TheMovieDataBase API. На текущий момент реализована только frontend часть. Функционал - показ новых релизов фильмов и популярных сейчас сериалов, поиск по жанрам, поиск по названию, отображение информации о фильме на отдельной странице, показ похожих фильмов. На данный момент не работает без VPN",
    instruments: "HTML, СSS (module CSS), JavaScript, React (hooks, react-router-dom, HOC, axios), TMDB API",
    features: "SPA, React, JSX, Responsive, Preloader, CSS Grid",
  },
]