export const portfolioTexts = [
  // {
  //   header: "Runsmart",
  //   imageSrc: "./runsmart.webp",
  //   link: "https://runsmart.kraevskiy-web.ru/",
  //   githubLink: "https://github.com/Gr1mmz/runsmart",
  //   description: "Верстка учебного макета интернет-магазина по продаже смарт-часов для бега. Верстка по макету из Figma.",
  //   instruments: "HTML, SASS, JavaScript, Gulp, PHP Mailer",
  //   features: "Модальные окна, форма обратной связи с валидацией, Adaptive, Slider, Burger"
  // },
  {
    header: "Портфолио веб-разработчика",
    imageSrc: "./portfolio.webp",
    link: "https://portfolio.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/portfolio-template",
    description: "Верстка учебного макета сайта-портфолио веб-разработчика. Верстка по макету из Figma.",
    instruments: "HTML, SASS, JavaScript, Gulp",
    features: "Семантическая верстка, добавление страницы с политикой конфиденциальности, стилизация инпутов в форме обратной связи, использование миксинов и псевдоэлементов, Pixel Perfect, Adaptive, Burger, CSS Grid.",
  },
  {
    header: "Zlatmax",
    imageSrc: "./zlatmax.webp",
    link: "https://zlatmax.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/zlatman",
    description: "Верстка учебного макета интернет-магазина по продаже ножей ручной работы. Верстка по макету из Figma.",
    instruments: "HTML, SСSS, JavaScript, Gulp, Webpack",
    features: "Модальные окна, трехуровневое меню, кастомные слайдеры, аккордеон, tips, адаптив без брейкпоинтов, Burger.",
  },
  {
    header: "ToDo List React + Redux",
    imageSrc: "./todoreact.webp",
    link: "https://todo.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/todoList-react-redux",
    description: "Приложение - Список дел на React с использованием библиотеки Redux. Типичное CRUD-приложение, созданное с помощью React и Redux. Позволяет добавлять или удалять дела, отмечать как выполненные, фильтровать по признакам. Добавлена возможность работы без мышки.",
    instruments: "HTML, SСSS, JavaScript, React, Redux",
    features: "SPA, React, Redux",
  },
  {
    header: "ToDo List React + MobX",
    imageSrc: "./todomobx.webp",
    link: "https://todomobx.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/next_mobx_material-app",
    description: "Еще одно приложение - Список дел на React с использованием библиотеки MobX. Сделано на этапе изучения MobX и Material UI, чтобы углубиться в стек разработки в стартапе. Позволяет добавлять или удалять дела, отмечать как выполненные, фильтровать по признакам.",
    instruments: "JavaScript, React, MobX, Material UI",
    features: "SPA, React, MobX, Material UI",
  },
  {
    header: "@parse/react-ssr",
    imageSrc: "./parse-react-ssr.webp",
    link: "https://github.com/parse-community/parse-react/pull/104",
    githubLink: "https://github.com/Gr1mmz/parse-react",
    description: "В процессе работы с библиотекой Parse была найдена ошибка. Создал форк библиотеки в свой GitHub, внес изменения и создал Pull Request, в котором описал суть ошибки - неправильный тип поля в возвращаемом объекте. Pull Request успешно смержился с мастер-веткой",
    instruments: "TypeScript, NextJS, Parse",
    features: "GitHub, Open Source libs",
  },
  {
    header: "Movie Library",
    imageSrc: "./movielib.webp",
    slides: ['./movielib.webp', './movielib/2.webp', './movielib/3.webp', './movielib/4.webp', './movielib/5.webp'],
    link: "https://movielib.kraevskiy-web.ru/",
    githubLink: "https://github.com/Gr1mmz/mov-lib-react",
    description: "Single Page Application, созданное с помощью библиотеки React и TheMovieDataBase API. На текущий момент реализована только frontend часть. Функционал - показ новых релизов фильмов и популярных сейчас сериалов, поиск по жанрам, поиск по названию, отображение информации о фильме на отдельной странице, показ похожих фильмов. На данный момент не работает без VPN",
    instruments: "HTML, СSS (module CSS), JavaScript, React (hooks, react-router-dom, HOC, axios), TMDB API",
    features: "SPA, React, JSX, Responsive, Preloader, CSS Grid",
  },
  {
    header: "Social Apes",
    imageSrc: "./socialapes.webp",
    slides: ['./socialapes.webp', './socialapes/2.webp', './socialapes/3.webp', './socialapes/4.webp'],
    link: "https://socialapes.vercel.app/",
    githubLink: "https://github.com/Gr1mmz/sn-test",
    description: "Полноценное fullstack приложение - социальная сеть, созданное с помощью NextJS (frontend) и Back4app (backend). На текущий момент реализован функционал регистрации и авторизации с валидацией на клиенте и на сервере, создана страница профиля, страница сообщений и 404 страница. Создан функционал добавления, изменения и удаления постов и лайков",
    instruments: "NextJS, TypeScript, Back4app, Material UI, ESLint, Redux, Redux-toolkit, Formik, yup, Parse",
    features: "SPA, NextJS, TypeScript, Login/Signup, Custom Alerts, Material UI",
  },
]